# Generated by Django 4.0.1 on 2022-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.TextField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('visit', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbie', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('current_position', models.CharField(max_length=50)),
                ('about', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(default=None)),
            ],
        ),
    ]
