# Generated by Django 4.0.1 on 2022-01-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifications',
            old_name='certification',
            new_name='certification_title',
        ),
        migrations.AddField(
            model_name='certifications',
            name='issued_by',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certifications',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certifications',
            name='visit',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
