# Generated by Django 4.0.1 on 2022-01-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_certification_certifications_certification_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='name',
        ),
    ]
