# Generated by Django 4.0.1 on 2022-01-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_certifications_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='logo',
        ),
    ]
